### PR TITLE
Support generating switch via `beginControlFlow`/`endControlFlow` without indent

### LINKED ISSUE #11: Do not indent switch when used in beginControlFlow
If the string starts with `"switch "` then do not automatically indent. Downside: we would have to maintain a boolean stack of calls to `beginControlFlow` such that on symmetric calls to `nextControlFlow`/`endControlFlow` know whether or not to unindent. As a result, this may not be worth doing! And that's fine.

This syntactical formatting oddity offends me, but apparently it's idiomatic. I just ported all my use of `beginControlFlow` for `switch` to `addCode`. I'm perfectly fine leaving it like that, but figured I'd file and see what others thought.

### PR DESCRIPTION
**Pull request by kdubb**
Fixes #11

### CODE REVIEW

**Comment by kdubb** [comment]
Fixes #11

**Comment by kdubb** [comment]
@JakeWharton Is this a solution that is usable to you.  Looking at our use of this hit seems like it would work but I'm not quite sure it's a valid solution for everyone.

**Comment by JakeWharton** [comment]
This looks fine, and I'd be fine using it, but I'm still skeptical of whether it should land. Maybe switches should just be indented and people can deal with it? Or if you _really_ want to support it you can build it yourself with `addCode`.

**Comment by kdubb** [comment]
I only entertain it because it's Xcode's default which does make it idiomatic as you stated. On the other hand there is an option to disable it now (one of the few formatting options in Xcode), so maybe we just leave it as is.

**Comment by kdubb** [comment]
Actually, aside from the final decision on formatting, I think this API signature should stay. Passing in the control flow construct separately future proofs any formatting indentation changes; `switch` or otherwise.

**Comment by kdubb** [comment]
Merged, as we can always remove the specialized indent 😉

**Pull request merged**
