### PR TITLE
Update Utils.kt

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/outfoxx/swiftpoet/issues/85

@kdubb I didnt think about it too much for the rest of the project tbh...I do not see this being a breaking change?

### CODE REVIEW

**Comment by kdubb** [comment]
Certainly for the time being this is not a breaking change. The project is essentially using Kotlin rules at the moment so fixing them is fine. In a future release the project does need to implement proper Swift rules.

**Comment by dnkoutso** [comment]
Fixed lint error.

**Comment by dnkoutso** [comment]
hm not sure whats wrong with CI? At first I had a format issue but now not sure...

**Comment by kdubb** [comment]
The new failure is not your fault. It has to do with permissions given to actions. I need to update the workflow to work with outside PR's again.

**Comment by dnkoutso** [comment]
gotcha thanks!

**Comment by dnkoutso** [comment]
Hi @kdubb was hoping to push this forward if it looks good! Thanks again!

**Pull request merged**
