### PR TITLE
Prepare for release 1.6.3.

### PR DESCRIPTION
**Pull request by dnkoutso**

### CODE REVIEW

**Review by kdubb — APPROVED** [review]

**Comment by dnkoutso** [comment]
I did not know the PR actually publishes stuff. I fixed some stuff and pushed again. This caused 1.6.3 to have been released already by the first CI run and now the job fails. This also blocks GH release to happen and other post release tasks...

**Comment by kdubb** [comment]
@dnkoutso Pushing a PR does _not_ release anything. It's the TAG you committed that caused the release.

**Comment by dnkoutso** [comment]
@kdubb ah :( argh

**Comment by kdubb** [comment]
You need to prepare the release PR, merge it and then push a tag against that revision that includes the release PR.

**Comment by dnkoutso** [comment]
It was maybe not clear from this https://github.com/outfoxx/swiftpoet/blob/main/RELEASING.md that the PR should merge on the CHANGELOG etc.

Maybe I understood wrong though.

**Comment by kdubb** [comment]
Yeah RELEASING is wrong. It's my fault for not reading it thoroughly

**Comment by dnkoutso** [comment]
What can we do now? Should I just drop 1.6.3 and try 1.6.4?

**Comment by dnkoutso** [comment]
If 1.6.3 is unpublishable somehow, I doubt anyone is using it we can then restart the process

**Comment by kdubb** [comment]
@dnkoutso This release action succeeded https://github.com/outfoxx/swiftpoet/actions/runs/7273399996. All the follow up actions failed because this version already exists.

So 1.6.3 made it out into the world and includes the fix you want (I think). I would say just merge this PR and although I don't thing it will try to release again, just cancel any "release" actions it creates. Note that you can let the "snapshot" release action as normal.

**Comment by dnkoutso** [comment]
Sounds good, merged.

**Comment by dnkoutso** [comment]
Done. For posterity I updated GH releases to match 1.6.3 now as the latest release since that was a post-release task.

**Pull request merged**
